import type { Topic, Riddle, QuizItem } from "./content";

export const TOPICS_FR: Topic[] = [
  { i: "🌍", t: "Quel pays tu aimerais le plus visiter ?", c: "Voyages" },
  { i: "🎵", t: "Quelle chanson te met toujours de bonne humeur ?", c: "Musique" },
  { i: "🍕", t: "C'est quoi ton plat préféré de tous les temps ?", c: "Nourriture" },
  { i: "🎬", t: "Meilleur film que t'as vu récemment ?", c: "Divertissement" },
  { i: "⚽", t: "Tu suis des équipes de sport ?", c: "Sport" },
  { i: "📚", t: "Dernier livre que t'as lu et adoré ?", c: "Livres" },
  { i: "🌅", t: "Tu es plutôt lève-tôt ou couche-tard ?", c: "Mode de vie" },
  { i: "🐶", t: "Chiens ou chats ?", c: "Amusement" },
  { i: "🚀", t: "Tu partirais dans l'espace si tu pouvais ?", c: "Imagination" },
  { i: "🎮", t: "Tu joues aux jeux vidéo ?", c: "Jeux vidéo" },
  { i: "🏖️", t: "Vacances à la plage ou city-trip ?", c: "Voyages" },
  { i: "☕", t: "Café ou thé ?", c: "Mode de vie" },
  { i: "💼", t: "C'est quoi ton job de rêve ?", c: "Carrière" },
  { i: "🌟", t: "Qui t'inspire le plus dans la vie ?", c: "Vie" },
  { i: "🍳", t: "T'aimes cuisiner ? Ton meilleur plat ?", c: "Nourriture" },
  { i: "🎸", t: "Tu joues d'un instrument de musique ?", c: "Musique" },
  { i: "🌙", t: "Tu fais quoi pour te détendre ?", c: "Mode de vie" },
  { i: "🏆", t: "Ta plus grande fierté jusqu'à maintenant ?", c: "Vie" },
  { i: "🤔", t: "Si tu pouvais avoir un super-pouvoir, ce serait lequel ?", c: "Imagination" },
  { i: "🌈", t: "Ta saison préférée et pourquoi ?", c: "Nature" },
  { i: "✈️", t: "C'était quoi ton meilleur voyage ?", c: "Voyages" },
  { i: "🚗", t: "C'est quoi ta voiture de rêve ?", c: "Voitures" },
  { i: "🍫", t: "Chocolat ou chips ?", c: "Nourriture" },
  { i: "🎯", t: "C'est quoi ton objectif pour cette année ?", c: "Objectifs" },
  { i: "🎂", t: "Ton meilleur souvenir d'anniversaire ?", c: "Vie" },
  { i: "🌺", t: "Ta fleur préférée ?", c: "Nature" },
  { i: "🎤", t: "Ta chanson de karaoké préférée ?", c: "Musique" },
  { i: "📺", t: "La meilleure série ou émission TV de tous les temps ?", c: "Divertissement" },
  { i: "🏃", t: "Tu fais du sport régulièrement ?", c: "Santé" },
  { i: "🍔", t: "Meilleur burger que t'as jamais mangé ?", c: "Nourriture" },
  { i: "🌋", t: "La chose la plus folle que t'as jamais faite ?", c: "Aventure" },
  { i: "🎨", t: "T'es quelqu'un de créatif ?", c: "Art" },
  { i: "🏔️", t: "Montagne ou bord de mer ?", c: "Voyages" },
  { i: "🎭", t: "T'es déjà allé au théâtre ?", c: "Culture" },
  { i: "🚴", t: "Vélo ou voiture pour les petits trajets ?", c: "Mode de vie" },
  { i: "🥘", t: "Une cuisine du monde que t'aimerais découvrir ?", c: "Nourriture" },
  { i: "📱", t: "Tu pourrais tenir une journée sans ton téléphone ?", c: "Technologie" },
  { i: "🎻", t: "Musique classique ou musique moderne ?", c: "Musique" },
  { i: "🏛️", t: "Ton personnage historique préféré ?", c: "Histoire" },
  { i: "🐬", t: "Ton animal préféré ?", c: "Animaux" },
  { i: "🌃", t: "Dans quelle ville tu habiterais si l'argent n'était pas un problème ?", c: "Voyages" },
  { i: "🍷", t: "Vin, bière ou cocktails ?", c: "Boissons" },
  { i: "💪", t: "Qu'est-ce qui te motive dans la vie ?", c: "Vie" },
  { i: "🎢", t: "Les montagnes russes, t'adores ou t'as la trouille ?", c: "Amusement" },
  { i: "🌊", t: "Tu sais nager ?", c: "Mode de vie" },
  { i: "🎁", t: "Meilleur cadeau que t'as reçu ?", c: "Vie" },
  { i: "🧘", t: "Tu médites ?", c: "Bien-être" },
  { i: "🍰", t: "Sucré ou salé ?", c: "Nourriture" },
  { i: "📷", t: "T'aimes la photographie ?", c: "Loisirs" },
  { i: "🛍️", t: "Tu préfères acheter en ligne ou en magasin ?", c: "Mode de vie" },
];

export const RIDDLES_FR: Riddle[] = [
  { i: "🧩", q: "J'ai des aiguilles mais je ne peux pas coudre. Qu'est-ce que je suis ?", a: "Une horloge" },
  { i: "🌊", q: "J'ai des villes mais pas de maisons. Qu'est-ce que je suis ?", a: "Une carte" },
  { i: "🌅", q: "Plus tu en prends, plus tu en laisses derrière toi. Qu'est-ce que je suis ?", a: "Des pas" },
  { i: "🔥", q: "Je grandis mais je ne suis pas vivant. Qu'est-ce que je suis ?", a: "Le feu" },
  { i: "💡", q: "Je parle sans bouche. Qu'est-ce que je suis ?", a: "Un écho" },
  { i: "🌑", q: "J'ai un œil mais je ne vois pas. Qu'est-ce que je suis ?", a: "Une aiguille" },
  { i: "🎭", q: "Je cours mais je n'ai pas de jambes. Qu'est-ce que je suis ?", a: "Une rivière" },
  { i: "❄️", q: "Tu peux m'attraper mais pas me lancer. Qu'est-ce que je suis ?", a: "Un rhume" },
  { i: "🎪", q: "J'ai une tête et une queue mais pas de corps. Qu'est-ce que je suis ?", a: "Une pièce de monnaie" },
  { i: "🌲", q: "J'ai des feuilles mais je ne suis pas un arbre. Qu'est-ce que je suis ?", a: "Un livre" },
  { i: "🪞", q: "Une fois dans une minute, deux fois dans un moment, jamais dans une année. Qu'est-ce que c'est ?", a: "La lettre M" },
  { i: "🧊", q: "Plus je sèche, plus je suis mouillé. Qu'est-ce que je suis ?", a: "Une serviette" },
  { i: "🎈", q: "Je monte mais je ne redescends jamais. Qu'est-ce que je suis ?", a: "Ton âge" },
  { i: "⏰", q: "Je suis toujours devant toi mais on ne peut pas me voir. Qu'est-ce que je suis ?", a: "Le futur" },
  { i: "🦁", q: "J'ai un cou mais pas de tête. Qu'est-ce que je suis ?", a: "Une bouteille" },
  { i: "🌈", q: "J'ai des dents mais je ne mords pas. Qu'est-ce que je suis ?", a: "Un peigne" },
  { i: "🏆", q: "Plus tu en as, moins tu vois. Qu'est-ce que je suis ?", a: "L'obscurité" },
  { i: "🚪", q: "J'ai des touches mais pas de serrures. Qu'est-ce que je suis ?", a: "Un clavier" },
  { i: "🌺", q: "Je fais le tour du monde en restant dans un coin. Qu'est-ce que je suis ?", a: "Un timbre" },
  { i: "🎲", q: "Qu'est-ce qui se brise dès qu'on le prononce ?", a: "Le silence" },
  { i: "⚡", q: "Je suis grand quand je suis jeune et petit quand je suis vieux. Qu'est-ce que je suis ?", a: "Une bougie" },
  { i: "🎯", q: "J'ai un pouce et quatre doigts mais je ne suis pas vivant. Qu'est-ce que je suis ?", a: "Un gant" },
  { i: "🌙", q: "Je suis plein de trous mais je retiens l'eau. Qu'est-ce que je suis ?", a: "Une éponge" },
  { i: "📖", q: "J'ai une colonne vertébrale mais pas d'os. Qu'est-ce que je suis ?", a: "Un livre" },
  { i: "🌋", q: "Je suis léger comme une plume, mais même le plus fort ne peut pas me tenir longtemps. Qu'est-ce que je suis ?", a: "Ton souffle" },
  { i: "💎", q: "Je traverse villes et campagnes sans jamais bouger. Qu'est-ce que je suis ?", a: "Une route" },
  { i: "🔑", q: "J'ai plein de touches mais j'n'ouvre aucune porte. Qu'est-ce que je suis ?", a: "Un piano" },
  { i: "⛅", q: "Je peux remplir une pièce sans prendre de place. Qu'est-ce que je suis ?", a: "La lumière" },
  { i: "🧦", q: "Plus on m'enlève, plus je grandis. Qu'est-ce que je suis ?", a: "Un trou" },
  { i: "🪙", q: "J'ai des aiguilles mais je ne peux rien tenir. Qu'est-ce que je suis ?", a: "Une horloge" },
  { i: "🍞", q: "J'ai un visage mais pas d'yeux. Qu'est-ce que je suis ?", a: "Une horloge" },
  { i: "🚲", q: "J'ai deux roues et pas de moteur. Qu'est-ce que je suis ?", a: "Un vélo" },
  { i: "🎂", q: "On me tire d'une mine et on m'enferme dans un étui en bois. Qu'est-ce que je suis ?", a: "La mine d'un crayon" },
  { i: "🌳", q: "J'ai des racines que personne ne voit et je suis plus grand que les arbres. Qu'est-ce que je suis ?", a: "Une montagne" },
  { i: "🐍", q: "J'ai une langue mais je ne goûte rien. Qu'est-ce que je suis ?", a: "Une chaussure" },
  { i: "🎸", q: "J'ai des cordes mais je ne suis pas un violon. Qu'est-ce que je suis ?", a: "Une guitare" },
  { i: "🔔", q: "Je sonne sans qu'on utilise ses doigts. Qu'est-ce que je suis ?", a: "Une cloche" },
  { i: "📞", q: "Je peux sonner sans cloches. Qu'est-ce que je suis ?", a: "Un téléphone" },
  { i: "📚", q: "On peut me lire sans que je sois écrit. Qu'est-ce que je suis ?", a: "Un visage" },
  { i: "🦋", q: "Je vole sans ailes. Qu'est-ce que je suis ?", a: "Le temps" },
  { i: "🌊", q: "J'ai des vagues mais pas d'eau. Qu'est-ce que je suis ?", a: "Les cheveux" },
  { i: "⚖️", q: "Je monte sans jamais redescendre. Qu'est-ce que je suis ?", a: "Ton âge" },
  { i: "🎤", q: "J'ai une voix mais pas de bouche. Qu'est-ce que je suis ?", a: "Un écho" },
  { i: "🚁", q: "Je vole sans ailes. Qu'est-ce que je suis ?", a: "Un cerf-volant" },
  { i: "🌸", q: "Je fleuris seulement la nuit. Qu'est-ce que je suis ?", a: "Une fleur nocturne" },
  { i: "🌍", q: "J'ai des continents mais pas d'habitants. Qu'est-ce que je suis ?", a: "Un globe" },
  { i: "💧", q: "Je suis plein d'eau mais je ne suis pas un verre. Qu'est-ce que je suis ?", a: "Un nuage" },
  { i: "📅", q: "J'ai des dates mais je ne suis pas un calendrier. Qu'est-ce que je suis ?", a: "Un livre d'histoire" },
  { i: "🎵", q: "J'ai des notes mais je ne suis pas de la musique. Qu'est-ce que je suis ?", a: "Une banque" },
  { i: "⏳", q: "J'ai du sable mais je ne suis pas une plage. Qu'est-ce que je suis ?", a: "Un sablier" },
];

export const QUIZ_FR: { easy: QuizItem[]; medium: QuizItem[]; hard: QuizItem[] } = {
  easy: [
    { q: "Capitale de la France ?", a: "Paris" },
    { q: "Jours dans une semaine ?", a: "Sept" },
    { q: "Couleur du ciel ?", a: "Bleu" },
    { q: "Pattes d'une araignée ?", a: "Huit" },
    { q: "5×5 = ?", a: "25" },
    { q: "Notre planète ?", a: "La Terre" },
    { q: "Mois dans une année ?", a: "Douze" },
    { q: "Meilleur ami de l'homme ?", a: "Le chien" },
    { q: "Plus grand océan ?", a: "Le Pacifique" },
    { q: "Côtés d'un triangle ?", a: "Trois" },
    { q: "Capitale du Royaume-Uni ?", a: "Londres" },
    { q: "Animal terrestre le plus rapide ?", a: "Le guépard" },
    { q: "Continents sur Terre ?", a: "Sept" },
    { q: "Rouge + blanc = ?", a: "Rose" },
    { q: "Montagne la plus haute ?", a: "L'Everest" },
    { q: "Heures dans une journée ?", a: "24" },
    { q: "Ce qui éloigne le médecin ?", a: "Une pomme" },
    { q: "Zéros dans un million ?", a: "Six" },
    { q: "Planète la plus proche du soleil ?", a: "Mercure" },
    { q: "Point d'ébullition de l'eau ?", a: "100 °C" },
    { q: "Monnaie du Royaume-Uni ?", a: "La livre sterling" },
    { q: "Capitale de l'Espagne ?", a: "Madrid" },
    { q: "Côtés d'un carré ?", a: "Quatre" },
    { q: "Couleur de l'herbe ?", a: "Vert" },
    { q: "Roues d'une voiture ?", a: "Quatre" },
    { q: "Animal qui fait meuh ?", a: "Une vache" },
    { q: "Plus grand mammifère ?", a: "La baleine bleue" },
    { q: "Couleur d'une banane ?", a: "Jaune" },
    { q: "Capitale de l'Italie ?", a: "Rome" },
    { q: "Qu'est-ce que les abeilles fabriquent ?", a: "Du miel" },
    { q: "Saisons dans une année ?", a: "Quatre" },
    { q: "C'est quoi l'eau gelée ?", a: "De la glace" },
    { q: "Doigts sur une main ?", a: "Cinq" },
    { q: "De quelle couleur est le soleil ?", a: "Jaune" },
    { q: "Qu'est-ce qu'on respire ?", a: "De l'oxygène" },
    { q: "Lettres dans l'alphabet ?", a: "26" },
    { q: "Capitale du Japon ?", a: "Tokyo" },
    { q: "Roi de la jungle ?", a: "Le lion" },
    { q: "Couleur de la neige ?", a: "Blanc" },
    { q: "Combien d'yeux avons-nous ?", a: "Deux" },
    { q: "Minutes dans une heure ?", a: "60" },
    { q: "Contraire de chaud ?", a: "Froid" },
    { q: "Jours en février (normale) ?", a: "28" },
    { q: "Bébé chien, ça s'appelle ?", a: "Un chiot" },
    { q: "Bébé chat, ça s'appelle ?", a: "Un chaton" },
    { q: "Couleur du chocolat ?", a: "Marron" },
    { q: "Animal qui fait coin-coin ?", a: "Un canard" },
    { q: "Contraire de haut ?", a: "Bas" },
    { q: "Roues d'un vélo ?", a: "Deux" },
    { q: "Quelle saison voit fleurir les fleurs ?", a: "Le printemps" },
    { q: "Capitale de l'Allemagne ?", a: "Berlin" },
    { q: "Couleur d'un camion de pompiers ?", a: "Rouge" },
    { q: "Combien de nez avons-nous ?", a: "Un" },
    { q: "Contraire de grand ?", a: "Petit" },
    { q: "Animal qui fait miaou ?", a: "Un chat" },
    { q: "Saison la plus froide ?", a: "L'hiver" },
    { q: "C'est quoi H2O ?", a: "De l'eau" },
    { q: "Centimes dans un dollar ?", a: "100" },
    { q: "Capitale des États-Unis ?", a: "Washington D.C." },
    { q: "Animal avec une trompe ?", a: "Un éléphant" },
    { q: "C'est quoi la pluie gelée ?", a: "De la neige" },
    { q: "Jours dans une année bissextile ?", a: "366" },
    { q: "Capitale de l'Australie ?", a: "Canberra" },
    { q: "Tentacules d'une pieuvre ?", a: "Huit" },
    { q: "Couleur des ours polaires ?", a: "Blanc" },
    { q: "Heures en deux jours ?", a: "48" },
    { q: "Jours en mai ?", a: "31" },
    { q: "Capitale de la Russie ?", a: "Moscou" },
    { q: "10+10 = ?", a: "20" },
    { q: "100-50 = ?", a: "50" },
    { q: "7×7 = ?", a: "49" },
    { q: "Côtés d'un hexagone ?", a: "Six" },
    { q: "Bleu + jaune = ?", a: "Vert" },
    { q: "Animal avec une poche ?", a: "Le kangourou" },
    { q: "Où vivent les pingouins ?", a: "En Antarctique" },
    { q: "Plus grand pays du monde ?", a: "La Russie" },
    { q: "Langue parlée au Brésil ?", a: "Le portugais" },
    { q: "Océan à l'est des États-Unis ?", a: "L'Atlantique" },
    { q: "Symbole chimique de l'eau ?", a: "H2O" },
    { q: "Cordes d'une guitare ?", a: "Six" },
    { q: "Planètes dans le système solaire ?", a: "Huit" },
    { q: "Couleur de l'émeraude ?", a: "Vert" },
    { q: "Fleuve le plus long du monde ?", a: "Le Nil" },
    { q: "Animal qui grogne et fait oink ?", a: "Un cochon" },
    { q: "Côtés d'un pentagone ?", a: "Cinq" },
    { q: "Capitale de la Chine ?", a: "Pékin" },
    { q: "Saison où tombent les feuilles ?", a: "L'automne" },
    { q: "12×12 = ?", a: "144" },
    { q: "Couleur des tomates ?", a: "Rouge" },
    { q: "Pattes d'un insecte ?", a: "Six" },
    { q: "Capitale du Canada ?", a: "Ottawa" },
    { q: "Côtés d'un octogone ?", a: "Huit" },
    { q: "Bébé cheval, ça s'appelle ?", a: "Un poulain" },
    { q: "Animal qui hiberne ?", a: "L'ours" },
    { q: "Jours en mars ?", a: "31" },
    { q: "Capitale de l'Égypte ?", a: "Le Caire" },
    { q: "9×9 = ?", a: "81" },
    { q: "Plus grand désert du monde ?", a: "Le Sahara" },
    { q: "La planète rouge ?", a: "Mars" },
    { q: "Plus grande planète ?", a: "Jupiter" },
  ],
  medium: [
    { q: "Symbole chimique de l'or ?", a: "Au" },
    { q: "Nombre d'os dans le corps humain ?", a: "206" },
    { q: "Qui a peint la Joconde ?", a: "Léonard de Vinci" },
    { q: "Plus grande planète ?", a: "Jupiter" },
    { q: "Fin de la Seconde Guerre mondiale ?", a: "1945" },
    { q: "Substance naturelle la plus dure ?", a: "Le diamant" },
    { q: "Qui a écrit Roméo et Juliette ?", a: "Shakespeare" },
    { q: "Nombre de cavités dans le cœur ?", a: "Quatre" },
    { q: "Langue la plus parlée au monde ?", a: "Le mandarin" },
    { q: "Année du premier iPhone ?", a: "2007" },
    { q: "Symbole de l'oxygène ?", a: "O" },
    { q: "Monnaie de la Russie ?", a: "Le rouble" },
    { q: "Plus grand bâtiment du monde ?", a: "Le Burj Khalifa" },
    { q: "Où a-t-on inventé le papier ?", a: "En Chine" },
    { q: "Plus petit os du corps ?", a: "L'étrier" },
    { q: "Sport pratiqué à Wimbledon ?", a: "Le tennis" },
    { q: "Racine carrée de 144 ?", a: "12" },
    { q: "Qui a écrit Hamlet ?", a: "Shakespeare" },
    { q: "Vitesse de la lumière (approx.) ?", a: "300 000 km/s" },
    { q: "Nombre de pays dans l'UE ?", a: "27" },
    { q: "Monnaie du Japon ?", a: "Le yen" },
    { q: "Inventeur du téléphone ?", a: "Bell" },
    { q: "Groupe sanguin le plus rare ?", a: "AB-" },
    { q: "Plus grand désert chaud ?", a: "Le Sahara" },
    { q: "CPU signifie ?", a: "Central Processing Unit" },
    { q: "Chute du mur de Berlin ?", a: "1989" },
    { q: "Gaz qui compose 78 % de l'atmosphère ?", a: "L'azote" },
    { q: "Plus grand pays d'Amérique du Sud ?", a: "Le Brésil" },
    { q: "Qui a écrit 1984 ?", a: "George Orwell" },
    { q: "HTTP signifie ?", a: "HyperText Transfer Protocol" },
    { q: "Combien d'os ont les requins ?", a: "Zéro" },
    { q: "JO de 2016, où ?", a: "Rio de Janeiro" },
    { q: "Os le plus long du corps ?", a: "Le fémur" },
    { q: "Symbole du fer ?", a: "Fe" },
    { q: "Plus grande île du monde ?", a: "Le Groenland" },
    { q: "RAM signifie ?", a: "Random Access Memory" },
    { q: "Langue avec le plus de locuteurs natifs ?", a: "Le mandarin" },
    { q: "Peintre de La Nuit étoilée ?", a: "Van Gogh" },
    { q: "Compositeur des Quatre Saisons ?", a: "Vivaldi" },
    { q: "Ville du Colisée ?", a: "Rome" },
    { q: "Cordes d'un violon ?", a: "Quatre" },
    { q: "Fosse la plus profonde ?", a: "La fosse des Mariannes" },
    { q: "Année du naufrage du Titanic ?", a: "1912" },
    { q: "Plus petit pays du monde ?", a: "Le Vatican" },
    { q: "Auteure de Orgueil et Préjugés ?", a: "Jane Austen" },
    { q: "Plus haute chute d'eau ?", a: "Le Saut Angel" },
    { q: "Plus grand organe du corps ?", a: "La peau" },
    { q: "NASA signifie ?", a: "National Aeronautics and Space Administration" },
    { q: "Côtés d'un dodécagone ?", a: "12" },
    { q: "Dieu grec de la mer ?", a: "Poséidon" },
    { q: "Langue parlée au Brésil ?", a: "Le portugais" },
    { q: "Cordes d'une basse ?", a: "Quatre" },
    { q: "Année du premier pas sur la Lune ?", a: "1969" },
    { q: "Symbole de l'argent ?", a: "Ag" },
    { q: "Créateur de Mickey Mouse ?", a: "Walt Disney" },
    { q: "Fuseaux horaires en Russie ?", a: "11" },
    { q: "Plus grand lac africain ?", a: "Le lac Victoria" },
    { q: "WWW signifie ?", a: "World Wide Web" },
    { q: "Théoricien de la relativité ?", a: "Einstein" },
    { q: "Indépendance de l'Inde ?", a: "1947" },
    { q: "Langue de l'Espagne ?", a: "L'espagnol" },
    { q: "Symbole du plomb ?", a: "Pb" },
    { q: "Touches d'un piano ?", a: "88" },
    { q: "Plus grand pingouin ?", a: "Le manchot empereur" },
    { q: "Joueurs dans une équipe de football ?", a: "11" },
    { q: "Film le plus rentable de l'histoire ?", a: "Avatar" },
    { q: "Capitale du Vietnam ?", a: "Hanoï" },
    { q: "Quel gaz les plantes absorbent-elles ?", a: "Le dioxyde de carbone" },
    { q: "Auteur de l'Odyssée ?", a: "Homère" },
    { q: "Monnaie d'Afrique du Sud ?", a: "Le rand" },
    { q: "Plus haute montagne d'Afrique ?", a: "Le Kilimandjaro" },
    { q: "Symbole du sodium ?", a: "Na" },
    { q: "Début de la Première Guerre mondiale ?", a: "1914" },
    { q: "Peintre de la Chapelle Sixtine ?", a: "Michel-Ange" },
    { q: "Seul mammifère capable de voler ?", a: "La chauve-souris" },
    { q: "Capitale de la Thaïlande ?", a: "Bangkok" },
    { q: "Auteur de Don Quichotte ?", a: "Cervantes" },
    { q: "Plus grand pays d'Afrique ?", a: "L'Algérie" },
    { q: "Symbole du potassium ?", a: "K" },
    { q: "Plus longue chaîne de montagnes ?", a: "Les Andes" },
    { q: "Langue de l'Argentine ?", a: "L'espagnol" },
    { q: "Dissolution de l'Union soviétique ?", a: "1991" },
    { q: "Deuxième plus grande planète ?", a: "Saturne" },
    { q: "Inventeur de l'ampoule électrique ?", a: "Edison" },
    { q: "Élément naturel le plus lourd ?", a: "L'uranium" },
    { q: "Plus grand mammifère ?", a: "La baleine bleue" },
    { q: "Plus long fleuve du monde ?", a: "Le Nil" },
    { q: "Capitale du Kenya ?", a: "Nairobi" },
    { q: "Symbole du mercure ?", a: "Hg" },
    { q: "Ville d'origine du jazz ?", a: "La Nouvelle-Orléans" },
    { q: "Plus petit océan ?", a: "L'Arctique" },
    { q: "Peintre de La Cène ?", a: "Léonard de Vinci" },
    { q: "Gaz principal sur Mars ?", a: "Le dioxyde de carbone" },
    { q: "Capitale du Pérou ?", a: "Lima" },
    { q: "Plus grand récif corallien ?", a: "La Grande Barrière de Corail" },
    { q: "Auteur du Seigneur des Anneaux ?", a: "J.R.R. Tolkien" },
    { q: "Lac le plus profond ?", a: "Le lac Baïkal" },
    { q: "Première Coupe du monde de football ?", a: "1930" },
    { q: "Plus petit oiseau ?", a: "La colibri abeille" },
    { q: "Nombre de symphonies de Beethoven ?", a: "9" },
  ],
  hard: [
    { q: "Explique la suite de Fibonacci.", a: "Chaque nombre est la somme des deux précédents : 0, 1, 1, 2, 3, 5..." },
    { q: "Seul nombre premier pair ?", a: "Le nombre 2" },
    { q: "Signature de la Magna Carta ?", a: "1215" },
    { q: "Découverte de la pénicilline ?", a: "Fleming, 1928" },
    { q: "Auteur de Crime et Châtiment ?", a: "Dostoïevski" },
    { q: "Année du protocole TCP/IP (Internet) ?", a: "1983" },
    { q: "Point le plus profond des océans ?", a: "La Fosse Challenger, ~11 km" },
    { q: "Première femme prix Nobel ?", a: "Marie Curie, 1903" },
    { q: "Théorème de Pythagore ?", a: "a²+b²=c²" },
    { q: "Centrale énergétique de la cellule ?", a: "La mitochondrie" },
    { q: "Demi-vie du carbone 14 ?", a: "~5 730 ans" },
    { q: "C'est quoi un trou noir ?", a: "Zone où la gravité empêche toute évasion" },
    { q: "Vitesse de la lumière ?", a: "299 792 km/s" },
    { q: "Test de Turing ?", a: "Test d'intelligence artificielle" },
    { q: "Formule de l'eau ?", a: "H₂O" },
    { q: "Auteur de Cent ans de solitude ?", a: "García Márquez" },
    { q: "Relativité générale ?", a: "La gravité = courbure de l'espace-temps" },
    { q: "Deuxième loi de la thermodynamique ?", a: "L'entropie d'un système isolé augmente" },
    { q: "Qui a démontré le dernier théorème de Fermat ?", a: "Andrew Wiles, 1994" },
    { q: "C'est quoi la matière noire ?", a: "Matière invisible détectée par la gravité" },
    { q: "Le chat de Schrödinger illustre quoi ?", a: "La superposition quantique" },
    { q: "Effet Doppler ?", a: "Changement de fréquence d'une onde selon le mouvement" },
    { q: "Concepteur du tableau périodique ?", a: "Mendeleïev" },
    { q: "Nombre d'Avogadro ?", a: "6,022 × 10²³" },
    { q: "CRISPR signifie ?", a: "Clustered Regularly Interspaced Short Palindromic Repeats" },
    { q: "Boson de Higgs ?", a: "Particule qui donne une masse aux autres" },
    { q: "Auteur de La Richesse des nations ?", a: "Adam Smith, 1776" },
    { q: "Vitesse du son dans l'air ?", a: "~343 m/s à 20 °C" },
    { q: "Intrication quantique ?", a: "Particules liées à distance" },
    { q: "Hypothèse de Riemann ?", a: "Sur la distribution des nombres premiers" },
    { q: "Père de la théorie de l'évolution ?", a: "Charles Darwin" },
    { q: "Formule de la photosynthèse ?", a: "6CO₂+6H₂O→C₆H₁₂O₆+6O₂" },
    { q: "Auteur de La République ?", a: "Platon" },
    { q: "Principe d'Heisenberg ?", a: "Impossible de connaître précisément position et quantité de mouvement" },
    { q: "Formule du glucose ?", a: "C₆H₁₂O₆" },
    { q: "Qui a fait construire le Taj Mahal ?", a: "Shah Jahan pour Mumtaz" },
    { q: "Élément le plus abondant dans l'univers ?", a: "L'hydrogène" },
    { q: "Bases de la théorie des cordes ?", a: "Les particules sont des cordes vibrantes en 1D" },
    { q: "Auteur d'Être et Temps ?", a: "Heidegger" },
    { q: "Fond diffus cosmologique ?", a: "Rayonnement résiduel du Big Bang" },
    { q: "Équation de Drake ?", a: "Estime le nombre de civilisations détectables" },
    { q: "Compositeur du Clavier bien tempéré ?", a: "J.S. Bach" },
    { q: "Identité d'Euler ?", a: "e^(iπ)+1=0" },
    { q: "Modèle standard ?", a: "Théorie des particules fondamentales" },
    { q: "Cycle de Krebs ?", a: "Voie de la respiration cellulaire" },
    { q: "Auteur d'Ainsi parlait Zarathoustra ?", a: "Nietzsche" },
    { q: "Effet Casimir ?", a: "Force quantique entre deux plaques" },
    { q: "Inventeur du vaccin contre la polio ?", a: "Jonas Salk" },
    { q: "Effet Coriolis ?", a: "Déviation due à la rotation de la Terre" },
    { q: "Conjecture de Goldbach ?", a: "Tout entier pair > 2 = somme de deux premiers" },
    { q: "Théorie de la tectonique des plaques ?", a: "Alfred Wegener" },
    { q: "Limite de Chandrasekhar ?", a: "~1,4 masse solaire" },
    { q: "Peintre de Las Meninas ?", a: "Velázquez, 1656" },
    { q: "Modèle de Bohr ?", a: "Électrons sur des orbites fixes" },
    { q: "Constante de Boltzmann ?", a: "~1,38×10⁻²³ J/K" },
    { q: "Auteur d'À la recherche du temps perdu ?", a: "Marcel Proust" },
    { q: "Longueur de Planck ?", a: "~1,6×10⁻³⁵ m" },
    { q: "Guerre la plus longue de l'histoire ?", a: "La Reconquista (~780 ans)" },
    { q: "Découverte de la radioactivité ?", a: "Becquerel, 1896" },
    { q: "Rayon de Schwarzschild ?", a: "Horizon des événements d'un trou noir" },
    { q: "Équations de Navier-Stokes ?", a: "Mouvement des fluides visqueux" },
    { q: "Année de parution de Don Quichotte ?", a: "1605" },
    { q: "Paradoxe EPR ?", a: "Expérience de pensée sur l'intrication" },
    { q: "Développeur de la théorie M ?", a: "Edward Witten" },
    { q: "Âge de l'univers ?", a: "~13,8 milliards d'années" },
    { q: "Auteur du Capital ?", a: "Karl Marx" },
    { q: "Rayonnement de Hawking ?", a: "Rayonnement thermique émis par les trous noirs" },
    { q: "Matérialisme dialectique ?", a: "Philosophie marxiste" },
    { q: "Modèle héliocentrique ?", a: "Copernic, 1543" },
    { q: "Condensat de Bose-Einstein ?", a: "État de la matière proche du zéro absolu" },
    { q: "Auteur du Conte de deux villes ?", a: "Charles Dickens" },
    { q: "Modèle ΛCDM ?", a: "Modèle cosmologique standard" },
    { q: "Équations de Maxwell ?", a: "Quatre équations de l'électromagnétisme" },
    { q: "Auteur des Frères Karamazov ?", a: "Dostoïevski" },
    { q: "Paradoxe de Banach-Tarski ?", a: "Une sphère peut être divisée en deux sphères égales" },
    { q: "Équation de Schrödinger ?", a: "Évolution de la fonction d'onde quantique" },
    { q: "Découverte de l'électron ?", a: "J.J. Thomson, 1897" },
    { q: "Pères fondateurs de l'électrodynamique quantique ?", a: "Feynman, Schwinger, Tomonaga" },
    { q: "Tachyon ?", a: "Particule hypothétique plus rapide que la lumière" },
    { q: "Auteur d'Anna Karénine ?", a: "Tolstoï" },
    { q: "Constante de Hubble ?", a: "Taux d'expansion de l'univers" },
    { q: "Compositeur des Noces de Figaro ?", a: "Mozart, 1786" },
    { q: "Loi de Stefan-Boltzmann ?", a: "Puissance rayonnée ∝ T⁴" },
    { q: "Auteur de Par-delà le bien et le mal ?", a: "Nietzsche" },
    { q: "Inventeur de la machine à vapeur ?", a: "James Watt, 1769" },
    { q: "Règle de Born ?", a: "|ψ|² donne la probabilité" },
    { q: "Auteur de Madame Bovary ?", a: "Flaubert" },
    { q: "Théorème de non-clonage ?", a: "Impossible de copier un état quantique inconnu" },
    { q: "Compositeur de Tosca ?", a: "Puccini" },
    { q: "Correspondance AdS/CFT ?", a: "Juan Maldacena" },
    { q: "Longueur d'onde de De Broglie ?", a: "λ = h/p" },
    { q: "Auteur d'Ulysse ?", a: "James Joyce" },
    { q: "Inégalité de Bell ?", a: "Test de la non-localité quantique" },
    { q: "Compositeur de La Bohème ?", a: "Puccini" },
    { q: "Diffusion Compton ?", a: "Diffusion de photons par des charges" },
    { q: "Auteur de La Métamorphose ?", a: "Kafka" },
    { q: "Transformation de Lorentz ?", a: "Transformation de l'espace-temps en relativité restreinte" },
    { q: "Gravité quantique à boucles ?", a: "Ashtekar, Rovelli, Smolin" },
    { q: "Supersymétrie ?", a: "Symétrie entre bosons et fermions" },
    { q: "Année de la relativité restreinte ?", a: "1905" },
  ],
};
