export interface Topic {
  i: string; // icon
  t: string; // text
  c: string; // category
}

export interface Riddle {
  i: string; // icon
  q: string; // question
  a: string; // answer
}

export interface QuizItem {
  q: string; // question
  a: string; // answer
}

export const TOPICS: Topic[] = [
  { i: "🌍", t: "What country would you most love to visit?", c: "Travel" },
  { i: "🎵", t: "What song always puts you in a good mood?", c: "Music" },
  { i: "🍕", t: "What is your all-time favourite food?", c: "Food" },
  { i: "🎬", t: "Best film you have watched recently?", c: "Entertainment" },
  { i: "⚽", t: "Do you follow any sports teams?", c: "Sports" },
  { i: "📚", t: "Last book you read and enjoyed?", c: "Books" },
  { i: "🌅", t: "Morning person or night owl?", c: "Lifestyle" },
  { i: "🐶", t: "Dogs or cats?", c: "Fun" },
  { i: "🚀", t: "Would you travel to space if you could?", c: "Imagination" },
  { i: "🎮", t: "Do you play any video games?", c: "Gaming" },
  { i: "🏖️", t: "Beach holiday or city break?", c: "Travel" },
  { i: "☕", t: "Coffee or tea?", c: "Lifestyle" },
  { i: "💼", t: "What is your dream job?", c: "Career" },
  { i: "🌟", t: "Who inspires you the most?", c: "Life" },
  { i: "🍳", t: "Do you enjoy cooking? Best dish?", c: "Food" },
  { i: "🎸", t: "Do you play any musical instruments?", c: "Music" },
  { i: "🌙", t: "What do you do to relax?", c: "Lifestyle" },
  { i: "🏆", t: "Your greatest achievement so far?", c: "Life" },
  { i: "🤔", t: "If you had any superpower, what would it be?", c: "Imagination" },
  { i: "🌈", t: "Favourite season and why?", c: "Nature" },
  { i: "✈️", t: "What's the best trip you've ever taken?", c: "Travel" },
  { i: "🚗", t: "What's your dream car?", c: "Cars" },
  { i: "🍫", t: "Chocolate or crisps?", c: "Food" },
  { i: "🎯", t: "What's your goal for this year?", c: "Goals" },
  { i: "🎂", t: "Best birthday memory?", c: "Life" },
  { i: "🌺", t: "Favourite flower?", c: "Nature" },
  { i: "🎤", t: "Karaoke favourite song?", c: "Music" },
  { i: "📺", t: "Best TV show ever made?", c: "Entertainment" },
  { i: "🏃", t: "Do you exercise regularly?", c: "Health" },
  { i: "🍔", t: "Best burger you've ever had?", c: "Food" },
  { i: "🌋", t: "Most adventurous thing you've done?", c: "Adventure" },
  { i: "🎨", t: "Are you a creative person?", c: "Art" },
  { i: "🏔️", t: "Mountains or seaside?", c: "Travel" },
  { i: "🎭", t: "Have you ever been to the theatre?", c: "Culture" },
  { i: "🚴", t: "Bike or car for short trips?", c: "Lifestyle" },
  { i: "🥘", t: "Cuisine you'd love to try?", c: "Food" },
  { i: "📱", t: "Could you live without a phone for a day?", c: "Tech" },
  { i: "🎻", t: "Classical or modern music?", c: "Music" },
  { i: "🏛️", t: "Favourite historical figure?", c: "History" },
  { i: "🐬", t: "Favourite animal?", c: "Animals" },
  { i: "🌃", t: "City you'd live in if money was no issue?", c: "Travel" },
  { i: "🍷", t: "Wine, beer or cocktails?", c: "Drinks" },
  { i: "💪", t: "What motivates you?", c: "Life" },
  { i: "🎢", t: "Roller coasters – love or hate?", c: "Fun" },
  { i: "🌊", t: "Can you swim?", c: "Lifestyle" },
  { i: "🎁", t: "Best gift you've received?", c: "Life" },
  { i: "🧘", t: "Do you meditate?", c: "Wellness" },
  { i: "🍰", t: "Sweet or savoury?", c: "Food" },
  { i: "📷", t: "Do you enjoy photography?", c: "Hobbies" },
  { i: "🛍️", t: "Online or in-store shopping?", c: "Lifestyle" },
];

export const RIDDLES: Riddle[] = [
  { i: "🧩", q: "I have hands but cannot clap. What am I?", a: "A clock" },
  { i: "🌊", q: "I have cities but no houses. What am I?", a: "A map" },
  { i: "🌅", q: "The more you take, the more you leave behind. What am I?", a: "Footsteps" },
  { i: "🔥", q: "I grow but I am not alive. What am I?", a: "Fire" },
  { i: "💡", q: "I speak without a mouth. What am I?", a: "An echo" },
  { i: "🌑", q: "I have an eye but cannot see. What am I?", a: "A needle" },
  { i: "🎭", q: "I run but have no legs. What am I?", a: "A river" },
  { i: "❄️", q: "You can catch me but not throw me. What am I?", a: "A cold" },
  { i: "🎪", q: "Head and tail but no body. What am I?", a: "A coin" },
  { i: "🌲", q: "I have leaves but I am not a tree. What am I?", a: "A book" },
  { i: "🪞", q: "Once in a minute, twice in a moment, never in a year. What is it?", a: "The letter M" },
  { i: "🧊", q: "Gets wetter as it dries. What am I?", a: "A towel" },
  { i: "🎈", q: "I go up but never come down. What am I?", a: "Your age" },
  { i: "⏰", q: "Always in front of you but cannot be seen. What am I?", a: "The future" },
  { i: "🦁", q: "I have a neck but no head. What am I?", a: "A bottle" },
  { i: "🌈", q: "Has teeth but cannot bite. What am I?", a: "A comb" },
  { i: "🏆", q: "The more you have of me, the less you see. What am I?", a: "Darkness" },
  { i: "🚪", q: "I have keys but no locks. What am I?", a: "A keyboard" },
  { i: "🌺", q: "Travels the world staying in one corner. What am I?", a: "A stamp" },
  { i: "🎲", q: "What breaks when you say it?", a: "Silence" },
  { i: "⚡", q: "I'm tall when young and short when old. What am I?", a: "A candle" },
  { i: "🎯", q: "I have a thumb and four fingers but I am not alive.", a: "A glove" },
  { i: "🌙", q: "I am full of holes but still hold water. What am I?", a: "A sponge" },
  { i: "📖", q: "I have a spine but no bones. What am I?", a: "A book" },
  { i: "🌋", q: "I'm light as a feather, yet the strongest can't hold me long.", a: "Your breath" },
  { i: "💎", q: "What goes through cities and fields but never moves?", a: "A road" },
  { i: "🔑", q: "What has many keys but cannot open a door?", a: "A piano" },
  { i: "⛅", q: "What can fill a room but takes up no space?", a: "Light" },
  { i: "🧦", q: "What gets bigger the more you take away?", a: "A hole" },
  { i: "🪙", q: "What has hands but cannot hold?", a: "A clock" },
  { i: "🍞", q: "What has a face but no eyes?", a: "A clock" },
  { i: "🚲", q: "What has two wheels and no engine?", a: "A bicycle" },
  { i: "🎂", q: "I am taken from a mine and shut up in a wooden case.", a: "Pencil lead" },
  { i: "🌳", q: "What has roots no one sees and is taller than trees?", a: "A mountain" },
  { i: "🐍", q: "What has a tongue but cannot taste?", a: "A shoe" },
  { i: "🎸", q: "What has strings but isn't a violin?", a: "A guitar" },
  { i: "🔔", q: "What rings but has no fingers?", a: "A bell" },
  { i: "📞", q: "What can ring without bells?", a: "A phone" },
  { i: "📚", q: "What can be read but isn't written?", a: "A face" },
  { i: "🦋", q: "What flies without wings?", a: "Time" },
  { i: "🌊", q: "What has waves but no water?", a: "Hair" },
  { i: "⚖️", q: "What goes up and never comes down?", a: "Your age" },
  { i: "🎤", q: "What has a voice but no mouth?", a: "An echo" },
  { i: "🚁", q: "What flies but has no wings?", a: "A kite" },
  { i: "🌸", q: "What blooms only at night?", a: "A nocturnal flower" },
  { i: "🌍", q: "What has continents but no people?", a: "A globe" },
  { i: "💧", q: "What's full of water but isn't a glass?", a: "A cloud" },
  { i: "📅", q: "What has dates but isn't a calendar?", a: "A history book" },
  { i: "🎵", q: "What has notes but isn't music?", a: "A bank" },
  { i: "⏳", q: "What has sand but isn't a beach?", a: "An hourglass" },
];

export const QUIZ_EASY: QuizItem[] = [
  { q: "Capital of France?", a: "Paris" },
  { q: "Days in a week?", a: "Seven" },
  { q: "Colour of the sky?", a: "Blue" },
  { q: "Legs on a spider?", a: "Eight" },
  { q: "5×5=?", a: "25" },
  { q: "Our planet?", a: "Earth" },
  { q: "Months in a year?", a: "Twelve" },
  { q: "Man's best friend?", a: "Dog" },
  { q: "Largest ocean?", a: "Pacific" },
  { q: "Triangle sides?", a: "Three" },
  { q: "Capital of UK?", a: "London" },
  { q: "Fastest land animal?", a: "Cheetah" },
  { q: "Continents on Earth?", a: "Seven" },
  { q: "Red + White = ?", a: "Pink" },
  { q: "Tallest mountain?", a: "Mount Everest" },
  { q: "Hours in a day?", a: "24" },
  { q: "Keeps the doctor away?", a: "An apple" },
  { q: "Zeros in a million?", a: "Six" },
  { q: "Closest planet to sun?", a: "Mercury" },
  { q: "Boiling point of water?", a: "100°C" },
  { q: "Currency of UK?", a: "Pound sterling" },
  { q: "Capital of Spain?", a: "Madrid" },
  { q: "Sides on a square?", a: "Four" },
  { q: "Colour of grass?", a: "Green" },
  { q: "Wheels on a car?", a: "Four" },
  { q: "Animal that says moo?", a: "A cow" },
  { q: "Largest mammal?", a: "Blue whale" },
  { q: "Colour of a banana?", a: "Yellow" },
  { q: "Capital of Italy?", a: "Rome" },
  { q: "What do bees make?", a: "Honey" },
  { q: "Seasons in a year?", a: "Four" },
  { q: "What's frozen water?", a: "Ice" },
  { q: "Fingers on one hand?", a: "Five" },
  { q: "What colour is the sun?", a: "Yellow" },
  { q: "What do we breathe?", a: "Oxygen" },
  { q: "Letters in the alphabet?", a: "26" },
  { q: "Capital of Japan?", a: "Tokyo" },
  { q: "King of the jungle?", a: "The lion" },
  { q: "Colour of snow?", a: "White" },
  { q: "How many eyes do we have?", a: "Two" },
  { q: "Minutes in an hour?", a: "60" },
  { q: "Opposite of hot?", a: "Cold" },
  { q: "Days in February (normal)?", a: "28" },
  { q: "Baby dog called?", a: "A puppy" },
  { q: "Baby cat called?", a: "A kitten" },
  { q: "Colour of chocolate?", a: "Brown" },
  { q: "Animal that quacks?", a: "A duck" },
  { q: "Opposite of up?", a: "Down" },
  { q: "Wheels on a bicycle?", a: "Two" },
  { q: "What season has flowers?", a: "Spring" },
  { q: "Capital of Germany?", a: "Berlin" },
  { q: "Colour of fire truck?", a: "Red" },
  { q: "Noses do we have?", a: "One" },
  { q: "Opposite of big?", a: "Small" },
  { q: "Animal that says meow?", a: "A cat" },
  { q: "Coldest season?", a: "Winter" },
  { q: "What is H2O?", a: "Water" },
  { q: "Cents in a dollar?", a: "100" },
  { q: "Capital of USA?", a: "Washington D.C." },
  { q: "Animal with a trunk?", a: "An elephant" },
  { q: "What is frozen rain?", a: "Snow" },
  { q: "Days in a leap year?", a: "366" },
  { q: "Capital of Australia?", a: "Canberra" },
  { q: "Octopus arms count?", a: "Eight" },
  { q: "Colour of polar bears?", a: "White" },
  { q: "Hours in two days?", a: "48" },
  { q: "Days in May?", a: "31" },
  { q: "Capital of Russia?", a: "Moscow" },
  { q: "10+10=?", a: "20" },
  { q: "100-50=?", a: "50" },
  { q: "7×7=?", a: "49" },
  { q: "Sides on a hexagon?", a: "Six" },
  { q: "Blue + yellow = ?", a: "Green" },
  { q: "Animal with a pouch?", a: "Kangaroo" },
  { q: "Where penguins live?", a: "Antarctica" },
  { q: "Largest country?", a: "Russia" },
  { q: "Language of Brazil?", a: "Portuguese" },
  { q: "Ocean east of USA?", a: "Atlantic" },
  { q: "Symbol for water?", a: "H2O" },
  { q: "Strings on a guitar?", a: "Six" },
  { q: "Planets in solar system?", a: "Eight" },
  { q: "Colour of emerald?", a: "Green" },
  { q: "Longest river?", a: "The Nile" },
  { q: "Animal that oinks?", a: "A pig" },
  { q: "Sides on a pentagon?", a: "Five" },
  { q: "Capital of China?", a: "Beijing" },
  { q: "Season with falling leaves?", a: "Autumn" },
  { q: "12×12=?", a: "144" },
  { q: "Colour of tomatoes?", a: "Red" },
  { q: "Legs on insect?", a: "Six" },
  { q: "Capital of Canada?", a: "Ottawa" },
  { q: "Sides on octagon?", a: "Eight" },
  { q: "Baby horse called?", a: "A foal" },
  { q: "Animal that hibernates?", a: "A bear" },
  { q: "Days in March?", a: "31" },
  { q: "Capital of Egypt?", a: "Cairo" },
  { q: "9×9=?", a: "81" },
  { q: "Largest desert?", a: "The Sahara" },
  { q: "Red planet?", a: "Mars" },
  { q: "Largest planet?", a: "Jupiter" },
];

export const QUIZ_MEDIUM: QuizItem[] = [
  { q: "Chemical symbol for gold?", a: "Au" },
  { q: "Bones in human body?", a: "206" },
  { q: "Who painted the Mona Lisa?", a: "Leonardo da Vinci" },
  { q: "Largest planet?", a: "Jupiter" },
  { q: "When did WW2 end?", a: "1945" },
  { q: "Hardest natural substance?", a: "Diamond" },
  { q: "Who wrote Romeo & Juliet?", a: "Shakespeare" },
  { q: "Heart chambers count?", a: "Four" },
  { q: "Most spoken language?", a: "Mandarin Chinese" },
  { q: "First iPhone year?", a: "2007" },
  { q: "Symbol for Oxygen?", a: "O" },
  { q: "Russia's currency?", a: "Ruble" },
  { q: "World's tallest building?", a: "Burj Khalifa" },
  { q: "Where was paper invented?", a: "China" },
  { q: "Smallest bone in body?", a: "The stapes" },
  { q: "Sport at Wimbledon?", a: "Tennis" },
  { q: "Square root of 144?", a: "12" },
  { q: "Who wrote Hamlet?", a: "Shakespeare" },
  { q: "Speed of light approx?", a: "300,000 km/s" },
  { q: "Countries in EU?", a: "27" },
  { q: "Currency of Japan?", a: "Yen" },
  { q: "Inventor of the telephone?", a: "Bell" },
  { q: "Rarest blood type?", a: "AB-" },
  { q: "Largest hot desert?", a: "Sahara" },
  { q: "What does CPU stand for?", a: "Central Processing Unit" },
  { q: "Berlin Wall fall?", a: "1989" },
  { q: "Gas 78% of atmosphere?", a: "Nitrogen" },
  { q: "Largest country South America?", a: "Brazil" },
  { q: "Who wrote 1984?", a: "George Orwell" },
  { q: "What does HTTP stand for?", a: "HyperText Transfer Protocol" },
  { q: "Sharks have how many bones?", a: "Zero" },
  { q: "2016 Olympics where?", a: "Rio de Janeiro" },
  { q: "Longest bone?", a: "Femur" },
  { q: "Symbol for iron?", a: "Fe" },
  { q: "Largest island?", a: "Greenland" },
  { q: "What does RAM stand for?", a: "Random Access Memory" },
  { q: "Most native speakers language?", a: "Mandarin" },
  { q: "Painter of Starry Night?", a: "Van Gogh" },
  { q: "Composer of Four Seasons?", a: "Vivaldi" },
  { q: "City of the Colosseum?", a: "Rome" },
  { q: "Strings on a violin?", a: "Four" },
  { q: "Deepest trench?", a: "Mariana Trench" },
  { q: "Titanic sank year?", a: "1912" },
  { q: "Smallest country?", a: "Vatican City" },
  { q: "Author of Pride and Prejudice?", a: "Jane Austen" },
  { q: "Highest waterfall?", a: "Angel Falls" },
  { q: "Largest organ?", a: "Skin" },
  { q: "NASA stands for?", a: "National Aeronautics and Space Admin." },
  { q: "Sides on dodecagon?", a: "12" },
  { q: "Greek god of sea?", a: "Poseidon" },
  { q: "Brazil's language?", a: "Portuguese" },
  { q: "Strings on bass?", a: "Four" },
  { q: "Moon landing year?", a: "1969" },
  { q: "Silver symbol?", a: "Ag" },
  { q: "Created Mickey Mouse?", a: "Walt Disney" },
  { q: "Russia time zones?", a: "11" },
  { q: "Largest African lake?", a: "Lake Victoria" },
  { q: "WWW means?", a: "World Wide Web" },
  { q: "Relativity theorist?", a: "Einstein" },
  { q: "India independence?", a: "1947" },
  { q: "Spain's language?", a: "Spanish" },
  { q: "Symbol for lead?", a: "Pb" },
  { q: "Keys on a piano?", a: "88" },
  { q: "Largest penguin?", a: "Emperor" },
  { q: "Football team players?", a: "11" },
  { q: "Highest grossing film?", a: "Avatar" },
  { q: "Vietnam capital?", a: "Hanoi" },
  { q: "Plants absorb what gas?", a: "Carbon dioxide" },
  { q: "Author of Odyssey?", a: "Homer" },
  { q: "South Africa currency?", a: "Rand" },
  { q: "Highest mountain Africa?", a: "Kilimanjaro" },
  { q: "Symbol for sodium?", a: "Na" },
  { q: "WWI began?", a: "1914" },
  { q: "Sistine Chapel painter?", a: "Michelangelo" },
  { q: "Only flying mammal?", a: "Bat" },
  { q: "Thailand capital?", a: "Bangkok" },
  { q: "Author of Don Quixote?", a: "Cervantes" },
  { q: "Largest African country?", a: "Algeria" },
  { q: "Symbol for potassium?", a: "K" },
  { q: "Longest mountain range?", a: "The Andes" },
  { q: "Argentina's language?", a: "Spanish" },
  { q: "Soviet Union dissolved?", a: "1991" },
  { q: "Second largest planet?", a: "Saturn" },
  { q: "Light bulb inventor?", a: "Edison" },
  { q: "Heaviest natural element?", a: "Uranium" },
  { q: "Largest mammal?", a: "Blue whale" },
  { q: "World's longest river?", a: "Nile" },
  { q: "Kenya capital?", a: "Nairobi" },
  { q: "Symbol for mercury?", a: "Hg" },
  { q: "Jazz origin city?", a: "New Orleans" },
  { q: "Smallest ocean?", a: "Arctic" },
  { q: "Last Supper painter?", a: "Leonardo da Vinci" },
  { q: "Mars main gas?", a: "Carbon dioxide" },
  { q: "Peru capital?", a: "Lima" },
  { q: "Largest reef?", a: "Great Barrier Reef" },
  { q: "LOTR author?", a: "J.R.R. Tolkien" },
  { q: "Deepest lake?", a: "Lake Baikal" },
  { q: "First World Cup?", a: "1930" },
  { q: "Smallest bird?", a: "Bee hummingbird" },
  { q: "Beethoven's symphonies?", a: "9" },
];

export const QUIZ_HARD: QuizItem[] = [
  { q: "Explain Fibonacci sequence.", a: "Each number sum of two before: 0,1,1,2,3,5..." },
  { q: "Only even prime number?", a: "The number 2" },
  { q: "Magna Carta signed?", a: "1215" },
  { q: "Discovered penicillin?", a: "Fleming, 1928" },
  { q: "Author of Crime and Punishment?", a: "Dostoevsky" },
  { q: "Internet (TCP/IP) year?", a: "1983" },
  { q: "Deepest ocean point?", a: "Challenger Deep, ~11km" },
  { q: "First woman Nobel?", a: "Marie Curie, 1903" },
  { q: "Pythagorean theorem?", a: "a²+b²=c²" },
  { q: "Cell powerhouse?", a: "Mitochondria" },
  { q: "Carbon-14 half-life?", a: "~5,730 years" },
  { q: "What is a black hole?", a: "Region where gravity prevents escape" },
  { q: "Speed of light?", a: "299,792 km/s" },
  { q: "Turing Test?", a: "Test of machine intelligence" },
  { q: "Water formula?", a: "H₂O" },
  { q: "100 Years of Solitude author?", a: "García Márquez" },
  { q: "General relativity?", a: "Gravity = curvature of spacetime" },
  { q: "Second law of thermodynamics?", a: "Entropy of isolated system increases" },
  { q: "Proved Fermat's Last Theorem?", a: "Andrew Wiles, 1994" },
  { q: "What is dark matter?", a: "Invisible matter inferred from gravity" },
  { q: "Schrödinger's cat illustrates?", a: "Quantum superposition" },
  { q: "Doppler Effect?", a: "Wave frequency change from motion" },
  { q: "Periodic table developer?", a: "Mendeleev" },
  { q: "Avogadro's number?", a: "6.022 × 10²³" },
  { q: "CRISPR stands for?", a: "Clustered Regularly Interspaced Short Palindromic Repeats" },
  { q: "Higgs boson?", a: "Particle giving mass to others" },
  { q: "Wealth of Nations author?", a: "Adam Smith, 1776" },
  { q: "Speed of sound in air?", a: "~343 m/s at 20°C" },
  { q: "Quantum entanglement?", a: "Particles linked across distance" },
  { q: "Riemann Hypothesis?", a: "On distribution of prime numbers" },
  { q: "Evolution theorist?", a: "Charles Darwin" },
  { q: "Photosynthesis formula?", a: "6CO₂+6H₂O→C₆H₁₂O₆+6O₂" },
  { q: "Author of The Republic?", a: "Plato" },
  { q: "Heisenberg principle?", a: "Cannot know position and momentum precisely" },
  { q: "Glucose formula?", a: "C₆H₁₂O₆" },
  { q: "Taj Mahal builder?", a: "Shah Jahan for Mumtaz" },
  { q: "Most abundant universe element?", a: "Hydrogen" },
  { q: "String theory basics?", a: "Particles are 1D vibrating strings" },
  { q: "Being and Time author?", a: "Heidegger" },
  { q: "Cosmic Microwave Background?", a: "Big Bang afterglow" },
  { q: "Drake Equation?", a: "Estimates detectable civilizations" },
  { q: "Composer of Well-Tempered Clavier?", a: "J.S. Bach" },
  { q: "Euler's identity?", a: "e^(iπ)+1=0" },
  { q: "Standard Model?", a: "Theory of fundamental particles" },
  { q: "Krebs cycle?", a: "Cellular respiration pathway" },
  { q: "Thus Spoke Zarathustra author?", a: "Nietzsche" },
  { q: "Casimir effect?", a: "Quantum force between plates" },
  { q: "Polio vaccine developer?", a: "Jonas Salk" },
  { q: "Coriolis Effect?", a: "Deflection on rotating planet" },
  { q: "Goldbach Conjecture?", a: "Every even >2 = sum of two primes" },
  { q: "Plate tectonics?", a: "Alfred Wegener" },
  { q: "Chandrasekhar limit?", a: "~1.4 solar masses" },
  { q: "Painter of Las Meninas?", a: "Velázquez, 1656" },
  { q: "Bohr model?", a: "Electrons in fixed orbits" },
  { q: "Boltzmann constant?", a: "~1.38×10⁻²³ J/K" },
  { q: "In Search of Lost Time author?", a: "Marcel Proust" },
  { q: "Planck length?", a: "~1.6×10⁻³⁵ m" },
  { q: "Longest war?", a: "Reconquista (~780 years)" },
  { q: "Discovered radioactivity?", a: "Becquerel, 1896" },
  { q: "Schwarzschild radius?", a: "Black hole event horizon" },
  { q: "Navier-Stokes equations?", a: "Viscous fluid motion" },
  { q: "Don Quixote year?", a: "1605" },
  { q: "EPR Paradox?", a: "Entanglement thought experiment" },
  { q: "M-theory developer?", a: "Edward Witten" },
  { q: "Universe age?", a: "~13.8 billion years" },
  { q: "Das Kapital author?", a: "Karl Marx" },
  { q: "Hawking radiation?", a: "Thermal radiation from black holes" },
  { q: "Dialectical materialism?", a: "Marxist philosophy" },
  { q: "Heliocentric model?", a: "Copernicus, 1543" },
  { q: "Bose-Einstein Condensate?", a: "Matter state near absolute zero" },
  { q: "Tale of Two Cities author?", a: "Charles Dickens" },
  { q: "Lambda-CDM model?", a: "Standard cosmological model" },
  { q: "Maxwell's equations?", a: "Four equations of electromagnetism" },
  { q: "Brothers Karamazov author?", a: "Dostoevsky" },
  { q: "Banach-Tarski Paradox?", a: "Sphere split into two equal spheres" },
  { q: "Schrödinger equation?", a: "Quantum wave function evolution" },
  { q: "Discovered electron?", a: "J.J. Thomson, 1897" },
  { q: "QED developers?", a: "Feynman, Schwinger, Tomonaga" },
  { q: "Tachyon?", a: "Hypothetical faster-than-light particle" },
  { q: "Anna Karenina author?", a: "Tolstoy" },
  { q: "Hubble constant?", a: "Rate of universe expansion" },
  { q: "Marriage of Figaro composer?", a: "Mozart, 1786" },
  { q: "Stefan-Boltzmann law?", a: "Power radiated ∝ T⁴" },
  { q: "Beyond Good and Evil author?", a: "Nietzsche" },
  { q: "Steam engine inventor?", a: "James Watt, 1769" },
  { q: "Born rule?", a: "|ψ|² gives probability" },
  { q: "Madame Bovary author?", a: "Flaubert" },
  { q: "No-cloning theorem?", a: "Cannot copy unknown quantum state" },
  { q: "Tosca composer?", a: "Puccini" },
  { q: "AdS/CFT correspondence?", a: "Juan Maldacena" },
  { q: "De Broglie wavelength?", a: "λ = h/p" },
  { q: "Ulysses author?", a: "James Joyce" },
  { q: "Bell inequality?", a: "Test for quantum non-locality" },
  { q: "La Bohème composer?", a: "Puccini" },
  { q: "Compton scattering?", a: "Photon scattering by charges" },
  { q: "The Metamorphosis author?", a: "Kafka" },
  { q: "Lorentz transformation?", a: "Spacetime transformation in SR" },
  { q: "Loop quantum gravity?", a: "Ashtekar, Rovelli, Smolin" },
  { q: "Supersymmetry?", a: "Symmetry between bosons and fermions" },
  { q: "Special relativity year?", a: "1905" },
];
