import type { Topic, Riddle, QuizItem } from "./content";

export const TOPICS_ES: Topic[] = [
  { i: "🌍", t: "¿Qué país te encantaría visitar?", c: "Viajes" },
  { i: "🎵", t: "¿Qué canción te pone de buen humor?", c: "Música" },
  { i: "🍕", t: "¿Cuál es tu comida favorita de todos los tiempos?", c: "Comida" },
  { i: "🎬", t: "¿La mejor película que has visto últimamente?", c: "Entretenimiento" },
  { i: "⚽", t: "¿Sigues algún equipo deportivo?", c: "Deportes" },
  { i: "📚", t: "¿Último libro que leíste y te gustó?", c: "Libros" },
  { i: "🌅", t: "¿Eres de los que madruga o de los que trasnochan?", c: "Estilo de vida" },
  { i: "🐶", t: "¿Perros o gatos?", c: "Diversión" },
  { i: "🚀", t: "¿Viajarías al espacio si pudieras?", c: "Imaginación" },
  { i: "🎮", t: "¿Juegas videojuegos?", c: "Gaming" },
  { i: "🏖️", t: "¿Playa o ciudad?", c: "Viajes" },
  { i: "☕", t: "¿Café o té?", c: "Estilo de vida" },
  { i: "💼", t: "¿Cuál es tu trabajo soñado?", c: "Carrera" },
  { i: "🌟", t: "¿Quién te inspira más en la vida?", c: "Vida" },
  { i: "🍳", t: "¿Te gusta cocinar? ¿Cuál es tu mejor plato?", c: "Comida" },
  { i: "🎸", t: "¿Tocas algún instrumento musical?", c: "Música" },
  { i: "🌙", t: "¿Qué haces para relajarte?", c: "Estilo de vida" },
  { i: "🏆", t: "¿Cuál es tu mayor logro hasta ahora?", c: "Vida" },
  { i: "🤔", t: "Si pudieras tener un superpoder, ¿cuál sería?", c: "Imaginación" },
  { i: "🌈", t: "¿Tu estación favorita y por qué?", c: "Naturaleza" },
  { i: "✈️", t: "¿Cuál es el mejor viaje que has hecho?", c: "Viajes" },
  { i: "🚗", t: "¿Cuál es tu coche soñado?", c: "Coches" },
  { i: "🍫", t: "¿Chocolate o patatas fritas?", c: "Comida" },
  { i: "🎯", t: "¿Cuál es tu meta para este año?", c: "Metas" },
  { i: "🎂", t: "¿Tu mejor recuerdo de cumpleaños?", c: "Vida" },
  { i: "🌺", t: "¿Tu flor favorita?", c: "Naturaleza" },
  { i: "🎤", t: "¿Qué canción cantarías en el karaoke?", c: "Música" },
  { i: "📺", t: "¿La mejor serie o programa de televisión de todos los tiempos?", c: "Entretenimiento" },
  { i: "🏃", t: "¿Haces ejercicio con regularidad?", c: "Salud" },
  { i: "🍔", t: "¿La mejor hamburguesa que has probado?", c: "Comida" },
  { i: "🌋", t: "¿Lo más aventurero que has hecho?", c: "Aventura" },
  { i: "🎨", t: "¿Eres una persona creativa?", c: "Arte" },
  { i: "🏔️", t: "¿Montaña o playa?", c: "Viajes" },
  { i: "🎭", t: "¿Has ido alguna vez al teatro?", c: "Cultura" },
  { i: "🚴", t: "¿Bici o coche para trayectos cortos?", c: "Estilo de vida" },
  { i: "🥘", t: "¿Qué cocina del mundo te gustaría probar?", c: "Comida" },
  { i: "📱", t: "¿Podrías vivir sin móvil un día entero?", c: "Tecnología" },
  { i: "🎻", t: "¿Música clásica o moderna?", c: "Música" },
  { i: "🏛️", t: "¿Tu personaje histórico favorito?", c: "Historia" },
  { i: "🐬", t: "¿Tu animal favorito?", c: "Animales" },
  { i: "🌃", t: "¿En qué ciudad vivirías si el dinero no fuera problema?", c: "Viajes" },
  { i: "🍷", t: "¿Vino, cerveza o cócteles?", c: "Bebidas" },
  { i: "💪", t: "¿Qué te motiva en la vida?", c: "Vida" },
  { i: "🎢", t: "Las montañas rusas: ¿las adoras o las odias?", c: "Diversión" },
  { i: "🌊", t: "¿Sabes nadar?", c: "Estilo de vida" },
  { i: "🎁", t: "¿El mejor regalo que has recibido?", c: "Vida" },
  { i: "🧘", t: "¿Meditas?", c: "Bienestar" },
  { i: "🍰", t: "¿Dulce o salado?", c: "Comida" },
  { i: "📷", t: "¿Te gusta la fotografía?", c: "Aficiones" },
  { i: "🛍️", t: "¿Compras por internet o en tienda?", c: "Estilo de vida" },
];

export const RIDDLES_ES: Riddle[] = [
  { i: "🧩", q: "Tengo manecillas pero no puedo aplaudir. ¿Qué soy?", a: "Un reloj" },
  { i: "🌊", q: "Tengo ciudades pero no casas. ¿Qué soy?", a: "Un mapa" },
  { i: "🌅", q: "Cuanto más tomas, más dejas atrás. ¿Qué soy?", a: "Los pasos" },
  { i: "🔥", q: "Crezco pero no estoy vivo. ¿Qué soy?", a: "El fuego" },
  { i: "💡", q: "Hablo sin boca. ¿Qué soy?", a: "El eco" },
  { i: "🌑", q: "Tengo ojo pero no veo. ¿Qué soy?", a: "Una aguja" },
  { i: "🎭", q: "Corro pero no tengo piernas. ¿Qué soy?", a: "Un río" },
  { i: "❄️", q: "Puedes cogerme pero no tirarme. ¿Qué soy?", a: "Un resfriado" },
  { i: "🎪", q: "Tengo cara y cruz pero no cuerpo. ¿Qué soy?", a: "Una moneda" },
  { i: "🌲", q: "Tengo hojas pero no soy un árbol. ¿Qué soy?", a: "Un libro" },
  { i: "🪞", q: "Una vez en un minuto, dos veces en un momento, nunca en un año. ¿Qué es?", a: "La letra M" },
  { i: "🧊", q: "Se moja más cuanto más seca. ¿Qué soy?", a: "Una toalla" },
  { i: "🎈", q: "Solo subo, nunca bajo. ¿Qué soy?", a: "Tu edad" },
  { i: "⏰", q: "Siempre está delante de ti pero no se puede ver. ¿Qué soy?", a: "El futuro" },
  { i: "🦁", q: "Tengo cuello pero no cabeza. ¿Qué soy?", a: "Una botella" },
  { i: "🌈", q: "Tiene dientes pero no muerde. ¿Qué soy?", a: "Un peine" },
  { i: "🏆", q: "Cuanto más de mí tienes, menos ves. ¿Qué soy?", a: "La oscuridad" },
  { i: "🚪", q: "Tengo teclas pero no cerraduras. ¿Qué soy?", a: "Un teclado" },
  { i: "🌺", q: "Viaja por todo el mundo sin salir de su esquina. ¿Qué soy?", a: "Un sello de correos" },
  { i: "🎲", q: "¿Qué se rompe cuando lo dices?", a: "El silencio" },
  { i: "⚡", q: "De joven soy alto y de viejo soy corto. ¿Qué soy?", a: "Una vela" },
  { i: "🎯", q: "Tengo un pulgar y cuatro dedos pero no estoy vivo. ¿Qué soy?", a: "Un guante" },
  { i: "🌙", q: "Estoy lleno de agujeros pero retengo el agua. ¿Qué soy?", a: "Una esponja" },
  { i: "📖", q: "Tengo lomo pero no huesos. ¿Qué soy?", a: "Un libro" },
  { i: "🌋", q: "Soy ligero como una pluma, pero ni el más fuerte me sostiene mucho tiempo.", a: "Tu respiración" },
  { i: "💎", q: "¿Qué atraviesa ciudades y campos sin moverse nunca?", a: "Una carretera" },
  { i: "🔑", q: "¿Qué tiene muchas teclas pero no puede abrir ninguna puerta?", a: "Un piano" },
  { i: "⛅", q: "¿Qué puede llenar una habitación sin ocupar espacio?", a: "La luz" },
  { i: "🧦", q: "¿Qué se hace más grande cuanto más le quitas?", a: "Un agujero" },
  { i: "🪙", q: "¿Qué tiene manecillas pero no puede sujetar nada?", a: "Un reloj" },
  { i: "🍞", q: "¿Qué tiene cara pero no tiene ojos?", a: "Un reloj" },
  { i: "🚲", q: "¿Qué tiene dos ruedas y no tiene motor?", a: "Una bicicleta" },
  { i: "🎂", q: "Me sacan de una mina y me guardan en una caja de madera.", a: "La mina de un lápiz" },
  { i: "🌳", q: "¿Qué tiene raíces que nadie ve y es más alto que los árboles?", a: "Una montaña" },
  { i: "🐍", q: "¿Qué tiene lengua pero no puede probar nada?", a: "Un zapato" },
  { i: "🎸", q: "¿Qué tiene cuerdas pero no es un violín?", a: "Una guitarra" },
  { i: "🔔", q: "¿Qué suena sin tener dedos?", a: "Una campana" },
  { i: "📞", q: "¿Qué puede sonar sin campanas?", a: "Un teléfono" },
  { i: "📚", q: "¿Qué se puede leer pero no está escrito?", a: "Un rostro" },
  { i: "🦋", q: "¿Qué vuela sin alas?", a: "El tiempo" },
  { i: "🌊", q: "¿Qué tiene olas pero no tiene agua?", a: "El pelo" },
  { i: "⚖️", q: "¿Qué sube y nunca baja?", a: "Tu edad" },
  { i: "🎤", q: "¿Qué tiene voz pero no tiene boca?", a: "El eco" },
  { i: "🚁", q: "¿Qué vuela pero no tiene alas?", a: "Una cometa" },
  { i: "🌸", q: "¿Qué florece solo de noche?", a: "Una flor nocturna" },
  { i: "🌍", q: "¿Qué tiene continentes pero no tiene personas?", a: "Un globo terráqueo" },
  { i: "💧", q: "¿Qué está lleno de agua pero no es un vaso?", a: "Una nube" },
  { i: "📅", q: "¿Qué tiene fechas pero no es un calendario?", a: "Un libro de historia" },
  { i: "🎵", q: "¿Qué tiene notas pero no es música?", a: "Un banco" },
  { i: "⏳", q: "¿Qué tiene arena pero no es una playa?", a: "Un reloj de arena" },
];

export const QUIZ_ES: { easy: QuizItem[]; medium: QuizItem[]; hard: QuizItem[] } = {
  easy: [
    { q: "¿Capital de Francia?", a: "París" },
    { q: "¿Días tiene una semana?", a: "Siete" },
    { q: "¿De qué color es el cielo?", a: "Azul" },
    { q: "¿Cuántas patas tiene una araña?", a: "Ocho" },
    { q: "5×5=?", a: "25" },
    { q: "¿Cómo se llama nuestro planeta?", a: "Tierra" },
    { q: "¿Meses tiene un año?", a: "Doce" },
    { q: "¿El mejor amigo del hombre?", a: "El perro" },
    { q: "¿El océano más grande?", a: "El Pacífico" },
    { q: "¿Lados tiene un triángulo?", a: "Tres" },
    { q: "¿Capital del Reino Unido?", a: "Londres" },
    { q: "¿El animal terrestre más rápido?", a: "El guepardo" },
    { q: "¿Cuántos continentes hay en la Tierra?", a: "Siete" },
    { q: "Rojo + blanco = ?", a: "Rosa" },
    { q: "¿La montaña más alta del mundo?", a: "El Everest" },
    { q: "¿Horas tiene un día?", a: "24" },
    { q: "¿Qué fruta aleja al médico?", a: "Una manzana" },
    { q: "¿Cuántos ceros tiene un millón?", a: "Seis" },
    { q: "¿El planeta más cercano al sol?", a: "Mercurio" },
    { q: "¿Punto de ebullición del agua?", a: "100 °C" },
    { q: "¿Moneda del Reino Unido?", a: "La libra esterlina" },
    { q: "¿Capital de España?", a: "Madrid" },
    { q: "¿Lados tiene un cuadrado?", a: "Cuatro" },
    { q: "¿De qué color es la hierba?", a: "Verde" },
    { q: "¿Ruedas tiene un coche?", a: "Cuatro" },
    { q: "¿Qué animal hace 'mu'?", a: "Una vaca" },
    { q: "¿El mamífero más grande?", a: "La ballena azul" },
    { q: "¿De qué color es un plátano?", a: "Amarillo" },
    { q: "¿Capital de Italia?", a: "Roma" },
    { q: "¿Qué producen las abejas?", a: "Miel" },
    { q: "¿Estaciones tiene un año?", a: "Cuatro" },
    { q: "¿Cómo se llama el agua congelada?", a: "Hielo" },
    { q: "¿Dedos tiene una mano?", a: "Cinco" },
    { q: "¿De qué color es el sol?", a: "Amarillo" },
    { q: "¿Qué respiramos?", a: "Oxígeno" },
    { q: "¿Letras tiene el alfabeto español?", a: "27" },
    { q: "¿Capital de Japón?", a: "Tokio" },
    { q: "¿El rey de la selva?", a: "El león" },
    { q: "¿De qué color es la nieve?", a: "Blanco" },
    { q: "¿Cuántos ojos tenemos?", a: "Dos" },
    { q: "¿Minutos tiene una hora?", a: "60" },
    { q: "¿Lo contrario de caliente?", a: "Frío" },
    { q: "¿Días tiene febrero en un año normal?", a: "28" },
    { q: "¿Cómo se llama la cría del perro?", a: "Un cachorro" },
    { q: "¿Cómo se llama la cría del gato?", a: "Un gatito" },
    { q: "¿De qué color es el chocolate?", a: "Marrón" },
    { q: "¿Qué animal hace 'cuac'?", a: "Un pato" },
    { q: "¿Lo contrario de arriba?", a: "Abajo" },
    { q: "¿Ruedas tiene una bicicleta?", a: "Dos" },
    { q: "¿En qué estación florecen las flores?", a: "La primavera" },
    { q: "¿Capital de Alemania?", a: "Berlín" },
    { q: "¿De qué color es un camión de bomberos?", a: "Rojo" },
    { q: "¿Cuántas narices tenemos?", a: "Una" },
    { q: "¿Lo contrario de grande?", a: "Pequeño" },
    { q: "¿Qué animal hace 'miau'?", a: "Un gato" },
    { q: "¿La estación más fría?", a: "El invierno" },
    { q: "¿Qué es H2O?", a: "Agua" },
    { q: "¿Cuántos céntimos tiene un dólar?", a: "100" },
    { q: "¿Capital de Estados Unidos?", a: "Washington D.C." },
    { q: "¿Qué animal tiene trompa?", a: "Un elefante" },
    { q: "¿Cómo se llama la lluvia congelada?", a: "Nieve" },
    { q: "¿Días tiene un año bisiesto?", a: "366" },
    { q: "¿Capital de Australia?", a: "Canberra" },
    { q: "¿Cuántos tentáculos tiene un pulpo?", a: "Ocho" },
    { q: "¿De qué color son los osos polares?", a: "Blanco" },
    { q: "¿Horas hay en dos días?", a: "48" },
    { q: "¿Días tiene mayo?", a: "31" },
    { q: "¿Capital de Rusia?", a: "Moscú" },
    { q: "10+10=?", a: "20" },
    { q: "100-50=?", a: "50" },
    { q: "7×7=?", a: "49" },
    { q: "¿Lados tiene un hexágono?", a: "Seis" },
    { q: "Azul + amarillo = ?", a: "Verde" },
    { q: "¿Qué animal tiene bolsa?", a: "El canguro" },
    { q: "¿Dónde viven los pingüinos?", a: "En la Antártida" },
    { q: "¿El país más grande del mundo?", a: "Rusia" },
    { q: "¿Qué idioma se habla en Brasil?", a: "Portugués" },
    { q: "¿Qué océano está al este de EE. UU.?", a: "El Atlántico" },
    { q: "¿Símbolo químico del agua?", a: "H2O" },
    { q: "¿Cuerdas tiene una guitarra?", a: "Seis" },
    { q: "¿Planetas hay en el sistema solar?", a: "Ocho" },
    { q: "¿De qué color es una esmeralda?", a: "Verde" },
    { q: "¿El río más largo del mundo?", a: "El Nilo" },
    { q: "¿Qué animal hace 'oink'?", a: "Un cerdo" },
    { q: "¿Lados tiene un pentágono?", a: "Cinco" },
    { q: "¿Capital de China?", a: "Pekín" },
    { q: "¿En qué estación caen las hojas?", a: "El otoño" },
    { q: "12×12=?", a: "144" },
    { q: "¿De qué color son los tomates?", a: "Rojo" },
    { q: "¿Patas tiene un insecto?", a: "Seis" },
    { q: "¿Capital de Canadá?", a: "Ottawa" },
    { q: "¿Lados tiene un octógono?", a: "Ocho" },
    { q: "¿Cómo se llama la cría del caballo?", a: "Un potro" },
    { q: "¿Qué animal hiberna?", a: "El oso" },
    { q: "¿Días tiene marzo?", a: "31" },
    { q: "¿Capital de Egipto?", a: "El Cairo" },
    { q: "9×9=?", a: "81" },
    { q: "¿El desierto más grande del mundo?", a: "El Sahara" },
    { q: "¿El planeta rojo?", a: "Marte" },
    { q: "¿El planeta más grande del sistema solar?", a: "Júpiter" },
  ],
  medium: [
    { q: "¿Símbolo químico del oro?", a: "Au" },
    { q: "¿Cuántos huesos tiene el cuerpo humano?", a: "206" },
    { q: "¿Quién pintó la Mona Lisa?", a: "Leonardo da Vinci" },
    { q: "¿El planeta más grande del sistema solar?", a: "Júpiter" },
    { q: "¿En qué año terminó la Segunda Guerra Mundial?", a: "1945" },
    { q: "¿La sustancia natural más dura?", a: "El diamante" },
    { q: "¿Quién escribió Romeo y Julieta?", a: "Shakespeare" },
    { q: "¿Cuántas cavidades tiene el corazón?", a: "Cuatro" },
    { q: "¿El idioma más hablado del mundo?", a: "El chino mandarín" },
    { q: "¿En qué año salió el primer iPhone?", a: "2007" },
    { q: "¿Símbolo del oxígeno?", a: "O" },
    { q: "¿Moneda de Rusia?", a: "El rublo" },
    { q: "¿El edificio más alto del mundo?", a: "El Burj Khalifa" },
    { q: "¿Dónde se inventó el papel?", a: "En China" },
    { q: "¿El hueso más pequeño del cuerpo?", a: "El estribo" },
    { q: "¿Qué deporte se juega en Wimbledon?", a: "Tenis" },
    { q: "¿Raíz cuadrada de 144?", a: "12" },
    { q: "¿Quién escribió Hamlet?", a: "Shakespeare" },
    { q: "¿Velocidad aproximada de la luz?", a: "300.000 km/s" },
    { q: "¿Cuántos países hay en la UE?", a: "27" },
    { q: "¿Moneda de Japón?", a: "El yen" },
    { q: "¿Quién inventó el teléfono?", a: "Bell" },
    { q: "¿El grupo sanguíneo más raro?", a: "AB-" },
    { q: "¿El mayor desierto caliente del mundo?", a: "El Sahara" },
    { q: "¿Qué significa CPU?", a: "Unidad Central de Procesamiento" },
    { q: "¿Cuándo cayó el Muro de Berlín?", a: "1989" },
    { q: "¿Gas que forma el 78 % de la atmósfera?", a: "Nitrógeno" },
    { q: "¿El país más grande de Sudamérica?", a: "Brasil" },
    { q: "¿Quién escribió 1984?", a: "George Orwell" },
    { q: "¿Qué significa HTTP?", a: "Protocolo de Transferencia de Hipertexto" },
    { q: "¿Cuántos huesos tienen los tiburones?", a: "Ninguno" },
    { q: "¿Dónde se celebraron los Juegos Olímpicos de 2016?", a: "Río de Janeiro" },
    { q: "¿El hueso más largo del cuerpo?", a: "El fémur" },
    { q: "¿Símbolo del hierro?", a: "Fe" },
    { q: "¿La isla más grande del mundo?", a: "Groenlandia" },
    { q: "¿Qué significa RAM?", a: "Memoria de Acceso Aleatorio" },
    { q: "¿El idioma con más hablantes nativos?", a: "El mandarín" },
    { q: "¿Quién pintó La noche estrellada?", a: "Van Gogh" },
    { q: "¿Quién compuso Las cuatro estaciones?", a: "Vivaldi" },
    { q: "¿En qué ciudad está el Coliseo?", a: "Roma" },
    { q: "¿Cuántas cuerdas tiene un violín?", a: "Cuatro" },
    { q: "¿La fosa oceánica más profunda?", a: "La fosa de las Marianas" },
    { q: "¿En qué año se hundió el Titanic?", a: "1912" },
    { q: "¿El país más pequeño del mundo?", a: "Ciudad del Vaticano" },
    { q: "¿Quién escribió Orgullo y prejuicio?", a: "Jane Austen" },
    { q: "¿La cascada más alta del mundo?", a: "El Salto Ángel" },
    { q: "¿El órgano más grande del cuerpo?", a: "La piel" },
    { q: "¿Qué significa NASA?", a: "Administración Nacional de Aeronáutica y del Espacio" },
    { q: "¿Lados tiene un dodecágono?", a: "12" },
    { q: "¿Dios griego del mar?", a: "Poseidón" },
    { q: "¿Qué idioma se habla en Brasil?", a: "Portugués" },
    { q: "¿Cuántas cuerdas tiene un bajo?", a: "Cuatro" },
    { q: "¿En qué año llegó el hombre a la Luna?", a: "1969" },
    { q: "¿Símbolo de la plata?", a: "Ag" },
    { q: "¿Quién creó a Mickey Mouse?", a: "Walt Disney" },
    { q: "¿Cuántas zonas horarias tiene Rusia?", a: "11" },
    { q: "¿El lago más grande de África?", a: "El lago Victoria" },
    { q: "¿Qué significa WWW?", a: "World Wide Web" },
    { q: "¿Quién formuló la teoría de la relatividad?", a: "Einstein" },
    { q: "¿En qué año se independizó la India?", a: "1947" },
    { q: "¿Qué idioma se habla en España?", a: "Español" },
    { q: "¿Símbolo del plomo?", a: "Pb" },
    { q: "¿Cuántas teclas tiene un piano?", a: "88" },
    { q: "¿El pingüino más grande?", a: "El pingüino emperador" },
    { q: "¿Cuántos jugadores hay en un equipo de fútbol?", a: "11" },
    { q: "¿La película más taquillera de la historia?", a: "Avatar" },
    { q: "¿Capital de Vietnam?", a: "Hanói" },
    { q: "¿Qué gas absorben las plantas?", a: "Dióxido de carbono" },
    { q: "¿Quién escribió la Odisea?", a: "Homero" },
    { q: "¿Moneda de Sudáfrica?", a: "El rand" },
    { q: "¿La montaña más alta de África?", a: "El Kilimanjaro" },
    { q: "¿Símbolo del sodio?", a: "Na" },
    { q: "¿En qué año comenzó la Primera Guerra Mundial?", a: "1914" },
    { q: "¿Quién pintó la Capilla Sixtina?", a: "Miguel Ángel" },
    { q: "¿El único mamífero que vuela?", a: "El murciélago" },
    { q: "¿Capital de Tailandia?", a: "Bangkok" },
    { q: "¿Quién escribió Don Quijote?", a: "Cervantes" },
    { q: "¿El país más grande de África?", a: "Argelia" },
    { q: "¿Símbolo del potasio?", a: "K" },
    { q: "¿La cordillera más larga del mundo?", a: "Los Andes" },
    { q: "¿Qué idioma se habla en Argentina?", a: "Español" },
    { q: "¿En qué año se disolvió la Unión Soviética?", a: "1991" },
    { q: "¿El segundo planeta más grande del sistema solar?", a: "Saturno" },
    { q: "¿Quién inventó la bombilla?", a: "Edison" },
    { q: "¿El elemento natural más pesado?", a: "El uranio" },
    { q: "¿El mamífero más grande del mundo?", a: "La ballena azul" },
    { q: "¿El río más largo del mundo?", a: "El Nilo" },
    { q: "¿Capital de Kenia?", a: "Nairobi" },
    { q: "¿Símbolo del mercurio?", a: "Hg" },
    { q: "¿Ciudad de origen del jazz?", a: "Nueva Orleans" },
    { q: "¿El océano más pequeño?", a: "El Ártico" },
    { q: "¿Quién pintó La Última Cena?", a: "Leonardo da Vinci" },
    { q: "¿Gas principal en la atmósfera de Marte?", a: "Dióxido de carbono" },
    { q: "¿Capital de Perú?", a: "Lima" },
    { q: "¿El arrecife más grande del mundo?", a: "La Gran Barrera de Coral" },
    { q: "¿Quién escribió El Señor de los Anillos?", a: "J. R. R. Tolkien" },
    { q: "¿El lago más profundo del mundo?", a: "El lago Baikal" },
    { q: "¿En qué año fue el primer Mundial de fútbol?", a: "1930" },
    { q: "¿El pájaro más pequeño del mundo?", a: "El colibrí abeja" },
    { q: "¿Cuántas sinfonías compuso Beethoven?", a: "9" },
  ],
  hard: [
    { q: "¿En qué consiste la sucesión de Fibonacci?", a: "Cada número es la suma de los dos anteriores: 0, 1, 1, 2, 3, 5..." },
    { q: "¿Cuál es el único número primo par?", a: "El número 2" },
    { q: "¿En qué año se firmó la Carta Magna?", a: "1215" },
    { q: "¿Quién descubrió la penicilina?", a: "Fleming, 1928" },
    { q: "¿Quién escribió Crimen y castigo?", a: "Dostoievski" },
    { q: "¿En qué año nació internet (TCP/IP)?", a: "1983" },
    { q: "¿El punto más profundo del océano?", a: "La Fosa Challenger, ~11 km" },
    { q: "¿La primera mujer en ganar el Nobel?", a: "Marie Curie, 1903" },
    { q: "¿El teorema de Pitágoras?", a: "a²+b²=c²" },
    { q: "¿La central energética de la célula?", a: "La mitocondria" },
    { q: "¿La vida media del carbono-14?", a: "~5.730 años" },
    { q: "¿Qué es un agujero negro?", a: "Región donde la gravedad impide el escape de nada, ni la luz" },
    { q: "¿La velocidad de la luz?", a: "299.792 km/s" },
    { q: "¿Qué es el Test de Turing?", a: "Prueba para evaluar la inteligencia de las máquinas" },
    { q: "¿Fórmula química del agua?", a: "H₂O" },
    { q: "¿Quién escribió Cien años de soledad?", a: "García Márquez" },
    { q: "¿En qué consiste la relatividad general?", a: "La gravedad es la curvatura del espacio-tiempo" },
    { q: "¿El segundo principio de la termodinámica?", a: "La entropía de un sistema aislado siempre aumenta" },
    { q: "¿Quién demostró el último teorema de Fermat?", a: "Andrew Wiles, 1994" },
    { q: "¿Qué es la materia oscura?", a: "Materia invisible inferida por sus efectos gravitacionales" },
    { q: "¿Qué ilustra el gato de Schrödinger?", a: "La superposición cuántica" },
    { q: "¿El efecto Doppler?", a: "Cambio en la frecuencia de una onda debido al movimiento relativo" },
    { q: "¿Quién desarrolló la tabla periódica?", a: "Mendeléyev" },
    { q: "¿El número de Avogadro?", a: "6,022 × 10²³" },
    { q: "¿Qué significa CRISPR?", a: "Repeticiones palindrómicas cortas agrupadas e interespaciadas regularmente" },
    { q: "¿Qué es el bosón de Higgs?", a: "La partícula que da masa a otras partículas" },
    { q: "¿Quién escribió La riqueza de las naciones?", a: "Adam Smith, 1776" },
    { q: "¿La velocidad del sonido en el aire?", a: "~343 m/s a 20 °C" },
    { q: "¿Qué es el entrelazamiento cuántico?", a: "Partículas interconectadas sin importar la distancia" },
    { q: "¿La hipótesis de Riemann?", a: "Trata sobre la distribución de los números primos" },
    { q: "¿El teórico de la evolución?", a: "Charles Darwin" },
    { q: "¿La fórmula de la fotosíntesis?", a: "6CO₂+6H₂O→C₆H₁₂O₆+6O₂" },
    { q: "¿Quién escribió La República?", a: "Platón" },
    { q: "¿El principio de Heisenberg?", a: "No se puede conocer con precisión posición y momento a la vez" },
    { q: "¿Fórmula de la glucosa?", a: "C₆H₁₂O₆" },
    { q: "¿Quién mandó construir el Taj Mahal?", a: "Shah Jahan para Mumtaz" },
    { q: "¿El elemento más abundante del universo?", a: "El hidrógeno" },
    { q: "¿En qué se basa la teoría de cuerdas?", a: "Las partículas son cuerdas unidimensionales vibrantes" },
    { q: "¿Quién escribió Ser y tiempo?", a: "Heidegger" },
    { q: "¿Qué es el fondo cósmico de microondas?", a: "El eco luminoso del Big Bang" },
    { q: "¿La ecuación de Drake?", a: "Estima el número de civilizaciones detectables en el universo" },
    { q: "¿Quién compuso El clave bien temperado?", a: "J. S. Bach" },
    { q: "¿La identidad de Euler?", a: "e^(iπ)+1=0" },
    { q: "¿El modelo estándar de la física?", a: "Teoría de las partículas fundamentales" },
    { q: "¿El ciclo de Krebs?", a: "Ruta metabólica de la respiración celular" },
    { q: "¿Quién escribió Así habló Zaratustra?", a: "Nietzsche" },
    { q: "¿El efecto Casimir?", a: "Fuerza cuántica entre dos placas conductoras próximas" },
    { q: "¿Quién desarrolló la vacuna contra la polio?", a: "Jonas Salk" },
    { q: "¿El efecto Coriolis?", a: "Desviación de los objetos en un planeta en rotación" },
    { q: "¿La conjetura de Goldbach?", a: "Todo número par mayor que 2 es suma de dos primos" },
    { q: "¿La tectónica de placas?", a: "Alfred Wegener" },
    { q: "¿El límite de Chandrasekhar?", a: "~1,4 masas solares" },
    { q: "¿Quién pintó Las Meninas?", a: "Velázquez, 1656" },
    { q: "¿El modelo atómico de Bohr?", a: "Los electrones orbitan en niveles fijos de energía" },
    { q: "¿La constante de Boltzmann?", a: "~1,38×10⁻²³ J/K" },
    { q: "¿Quién escribió En busca del tiempo perdido?", a: "Marcel Proust" },
    { q: "¿La longitud de Planck?", a: "~1,6×10⁻³⁵ m" },
    { q: "¿La guerra más larga de la historia?", a: "La Reconquista (~780 años)" },
    { q: "¿Quién descubrió la radiactividad?", a: "Becquerel, 1896" },
    { q: "¿El radio de Schwarzschild?", a: "El horizonte de eventos de un agujero negro" },
    { q: "¿Las ecuaciones de Navier-Stokes?", a: "Describen el movimiento de fluidos viscosos" },
    { q: "¿En qué año se publicó Don Quijote?", a: "1605" },
    { q: "¿La paradoja EPR?", a: "Experimento mental sobre el entrelazamiento cuántico" },
    { q: "¿Quién desarrolló la teoría M?", a: "Edward Witten" },
    { q: "¿La edad del universo?", a: "~13.800 millones de años" },
    { q: "¿Quién escribió El capital?", a: "Karl Marx" },
    { q: "¿La radiación de Hawking?", a: "Radiación térmica emitida por los agujeros negros" },
    { q: "¿El materialismo dialéctico?", a: "Filosofía marxista del cambio histórico" },
    { q: "¿El modelo heliocéntrico?", a: "Copérnico, 1543" },
    { q: "¿El condensado de Bose-Einstein?", a: "Estado de la materia cerca del cero absoluto" },
    { q: "¿Quién escribió Historia de dos ciudades?", a: "Charles Dickens" },
    { q: "¿El modelo Lambda-CDM?", a: "Modelo cosmológico estándar" },
    { q: "¿Las ecuaciones de Maxwell?", a: "Cuatro ecuaciones del electromagnetismo" },
    { q: "¿Quién escribió Los hermanos Karamázov?", a: "Dostoievski" },
    { q: "¿La paradoja de Banach-Tarski?", a: "Una esfera se puede dividir en dos esferas iguales" },
    { q: "¿La ecuación de Schrödinger?", a: "Describe la evolución de la función de onda cuántica" },
    { q: "¿Quién descubrió el electrón?", a: "J. J. Thomson, 1897" },
    { q: "¿Quiénes desarrollaron la QED?", a: "Feynman, Schwinger y Tomonaga" },
    { q: "¿Qué es un taquión?", a: "Partícula hipotética más rápida que la luz" },
    { q: "¿Quién escribió Ana Karénina?", a: "Tolstói" },
    { q: "¿La constante de Hubble?", a: "La tasa de expansión del universo" },
    { q: "¿Quién compuso Las bodas de Fígaro?", a: "Mozart, 1786" },
    { q: "¿La ley de Stefan-Boltzmann?", a: "La potencia emitida es proporcional a T⁴" },
    { q: "¿Quién escribió Más allá del bien y del mal?", a: "Nietzsche" },
    { q: "¿Quién inventó la máquina de vapor?", a: "James Watt, 1769" },
    { q: "¿La regla de Born?", a: "|ψ|² da la probabilidad de un resultado cuántico" },
    { q: "¿Quién escribió Madame Bovary?", a: "Flaubert" },
    { q: "¿El teorema de no clonación?", a: "No se puede copiar un estado cuántico desconocido" },
    { q: "¿Quién compuso Tosca?", a: "Puccini" },
    { q: "¿La correspondencia AdS/CFT?", a: "Juan Maldacena" },
    { q: "¿La longitud de onda de De Broglie?", a: "λ = h/p" },
    { q: "¿Quién escribió Ulises?", a: "James Joyce" },
    { q: "¿La desigualdad de Bell?", a: "Test para detectar la no localidad cuántica" },
    { q: "¿Quién compuso La Bohème?", a: "Puccini" },
    { q: "¿El efecto Compton?", a: "Dispersión de fotones por partículas cargadas" },
    { q: "¿Quién escribió La metamorfosis?", a: "Kafka" },
    { q: "¿La transformación de Lorentz?", a: "Transformación del espacio-tiempo en la relatividad especial" },
    { q: "¿La gravedad cuántica de lazos?", a: "Ashtekar, Rovelli y Smolin" },
    { q: "¿La supersimetría?", a: "Simetría entre bosones y fermiones" },
    { q: "¿En qué año se publicó la relatividad especial?", a: "1905" },
  ],
};
